### ISSUE TITLE
Exponential damper parameters and example

### ISSUE THREAD

**Issue by dhblum** [ibpsa/modelica#544]
The use_v_nominal, v_nominal, and A parameters in Fluid.Actuators.Dampers.Exponential can be confusing, particularly as illustrated in Examples.Damper where both A and v_nominal have values of 1.
- Propose removing parameters use_v_nominal and v_nominal, and having m_flow_nominal/rho_default/1 as the default value in A.
- Propose changing Examples.Damper to remove the specifier of A=1.

ASHRAE 825-RP gives a range of reasonable values for k0 and k1, which could be used to ensure proper damper model performance. 
- Propose adding an assert statement to the values of parameters k1 and k0 to ensure they are within the range of those reported in ASHRAE 825-RP.

No tests for when the parameter linearized=True.
- Propose changing Examples.Damper by adding a damper in parallel to res with linearized=True to compare the performance.

**Comment by mwetter** [comment]
These are all good changes.

**Comment by Mathadon** [comment]
closed through #545
