### ISSUE TITLE
new label for open issues

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica#551]
We have a lot of open issues that I do not see being fixed any time soon. Still I propose to keep them because people may encounter bugs related to these issues. I would however create a label for these issues that indicates to ourselves that we do not consider it a priority. This way the things that are a priority will stick out better!

**Comment by Mathadon** [comment]
For instance the label 'Long term'?

**Comment by rubenbaetens** [comment]
Wikipedia uses the label `stale` for this.

**Comment by thorade** [comment]
Maybe using Milestones could be an alternative?
Some projects use the `future` milestone.
