### ISSUE TITLE
Increase number of reference results points for JModelica

### ISSUE THREAD

**Issue by tsnouidui** [ibpsa/modelica#603]
This issue is to increase the number of reference results points which is needed by JModelica for verification purposes.

**Comment by agnesramle** [comment]
When new reference results was created for Annex60.Fluid.HeatExchangers.ActiveBeams.BaseClasses.Examples.Convector it seems like store events point was activated but that the time vector was not saved in the reference result.

**Comment by tsnouidui** [comment]
will look into this.

**Comment by tsnouidui** [comment]
This should be fixed now.
