### ISSUE TITLE
Use same term for filteredOpening and filteredSpeed

### ISSUE THREAD

**Issue by mwetter** [ibpsa/modelica#665]
This ticket is to discuss using for example `filteredInput` (or `use_input_filter`) instead of `filteredSpeed` for the movers and `filteredOpening` for the valves.

**Comment by mwetter** [comment]
Aachen does not see a problem with this change.

**Comment by Mathadon** [comment]
I think it's a good suggestion. We could use the same base class for all models then?

**Comment by thorade** [comment]
No objections from Berlin.

**Comment by mwetter** [comment]
I changed to `use_inputFilter` in a191aa10322ebaced305df7636a5eb2ef9375abf. We are not consistent in our notation, but most flags are of the form `use_"camelCaseNotation"`.
