### ISSUE TITLE
Initial equation for checkBoundary when parameter inputs only

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica#728]
In models such as `IBPSA.Fluid.Sources.MassFlowSource_T` and `IBPSA.Fluid.Sources.Boundary_pT` we have 
```
equation
   Modelica.Fluid.Utilities.checkBoundary(
     Medium.mediumName,
     Medium.substanceNames,
     Medium.singleState,
     true,
     X_in_internal,
     "MassFlowSource_T");
```

when `use_X_in = false` this can be moved to the initial equation section, which can avoid overhead in some tools. Removing this check entirely is also an option, although I think it's useful so we should probably keep it.

@mwetter do you agree?

**Comment by mwetter** [comment]
I agree.
